-- EJERCICIO 1 M5S7, OCUPANDO BD ejercicio_M5S6
-- PASO 1 desde tabla más detallada a más específica
SELECT *
FROM "TB_DETALLE_VENTA";

-- PASO 2
SELECT "TB_VENTA_VEN_NUMERO", SUM("DET_VALOR_UNITARIO" * "DET_CANTIDAD") SubTotal
FROM "TB_DETALLE_VENTA"
GROUP BY "TB_VENTA_VEN_NUMERO"
ORDER BY "TB_VENTA_VEN_NUMERO";

-- PASO 3
SELECT *
FROM "TB_VENTA"
INNER JOIN (
	SELECT "TB_VENTA_VEN_NUMERO", SUM("DET_VALOR_UNITARIO" * "DET_CANTIDAD") SubTotal
	FROM "TB_DETALLE_VENTA"
	GROUP BY "TB_VENTA_VEN_NUMERO"
	ORDER BY "TB_VENTA_VEN_NUMERO") "DETALLE" ON "TB_VENTA_VEN_NUMERO" = "VEN_NUMERO"
WHERE EXTRACT (YEAR FROM "VEN_FECHA") = 2021;

-- PASO 4
SELECT EXTRACT (YEAR FROM "VEN_FECHA") AS Periodo, "CLI_NOMBRE" AS NombreCliente, COUNT(*) AS CantidadCompras,SUM(TotalVenta) AS Total,
CASE 
	WHEN SUM(TotalVenta)<=150000 THEN 'Ocasional'
	WHEN SUM(TotalVenta)<=500000 THEN 'Gold'
ELSE 'Premiun' END AS Clasificacion
FROM "TB_VENTA"
INNER JOIN (
	SELECT "TB_VENTA_VEN_NUMERO", SUM("DET_VALOR_UNITARIO" * "DET_CANTIDAD") TotalVenta
	FROM "TB_DETALLE_VENTA"
	GROUP BY "TB_VENTA_VEN_NUMERO"
	ORDER BY "TB_VENTA_VEN_NUMERO") "DETALLE" ON "TB_VENTA_VEN_NUMERO" = "VEN_NUMERO"
INNER JOIN "TB_CLIENTE" ON "CLI_RUT" = "TB_CLIENTE_CLI_RUT"
WHERE EXTRACT (YEAR FROM "VEN_FECHA") = 2021
GROUP BY EXTRACT (YEAR FROM "VEN_FECHA"), "CLI_NOMBRE";