SELECT V."VEN_NUMERO" AS "Nro. Boleta", V."VEN_FECHA" AS "Fecha Boleta", DV."DET_CANTIDAD" AS "Cantidad", DV."DET_VALOR_UNITARIO" AS "Precio Unitario"
FROM "TB_VENTA" AS V 
INNER JOIN "TB_DETALLE_VENTA" AS DV ON V."VEN_NUMERO" = DV."TB_VENTA_VEN_NUMERO";
-- 

SELECT V."VEN_NUMERO" AS "Nro. Boleta", V."VEN_FECHA" AS "Fecha Boleta", DV."DET_CANTIDAD" * DV."DET_VALOR_UNITARIO" AS SubTotal 
FROM "TB_VENTA" AS V 
INNER JOIN "TB_DETALLE_VENTA" AS DV ON V."VEN_NUMERO" = DV."TB_VENTA_VEN_NUMERO";
--

SELECT V."VEN_NUMERO" AS "Nro. Boleta", V."VEN_FECHA" AS "Fecha Boleta", SUM("DET_CANTIDAD" * "DET_VALOR_UNITARIO") AS "Total Venta" 
FROM "TB_VENTA" AS V 
INNER JOIN "TB_DETALLE_VENTA" AS DV ON V."VEN_NUMERO" = DV."TB_VENTA_VEN_NUMERO"
-- WHERE EXTRACT(YEAR FROM V."VEN_FECHA") = 2020 
GROUP BY V."VEN_NUMERO", V."VEN_FECHA"
ORDER BY V."VEN_NUMERO";