-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."TB_CLIENTE"
(
    "CLI_RUT" character varying(10),
    "CLI_NOMBRE" character varying(100),
    "CLI_GIRO" character varying(100) NOT NULL,
    "CLI_DIRECCION" character varying(100),
    "CLI_FONO" character varying(100),
    PRIMARY KEY ("CLI_RUT")
);

CREATE TABLE IF NOT EXISTS public."TB_VENTA"
(
    "VEN_NUMERO" serial,
    "VEN_FECHA" date,
    "TB_CLIENTE_CLI_RUT" serial,
    PRIMARY KEY ("VEN_NUMERO")
);

CREATE TABLE IF NOT EXISTS public."TB_DETALLE_VENTA"
(
    "DET_ID" serial,
    "DET_CANTIDAD" character varying(100),
    "DET_VALOR_UNITARIO" character varying(100),
    "TB_VENTA_VEN_NUMERO" serial,
    "TB_PRODUCTO_PRO_CODIGO" serial,
    PRIMARY KEY ("DET_ID")
);

CREATE TABLE IF NOT EXISTS public."TB_PRODUCTO"
(
    "PRO_CODIGO" serial,
    "PRO_NOMBRE" character varying(100),
    "PRO_STOCK" character varying(100),
    "PRO_VALOR_UNITARIO" character varying(100),
    PRIMARY KEY ("PRO_CODIGO")
);

ALTER TABLE IF EXISTS public."TB_VENTA"
    ADD FOREIGN KEY ("TB_CLIENTE_CLI_RUT")
    REFERENCES public."TB_CLIENTE" ("CLI_RUT") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."TB_DETALLE_VENTA"
    ADD FOREIGN KEY ("TB_VENTA_VEN_NUMERO")
    REFERENCES public."TB_VENTA" ("VEN_NUMERO") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."TB_PRODUCTO"
    ADD FOREIGN KEY ("PRO_CODIGO")
    REFERENCES public."TB_DETALLE_VENTA" ("TB_PRODUCTO_PRO_CODIGO") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;