CREATE TABLE "TB_CLIENTE"(
	"CLI_RUT" VARCHAR(15) PRIMARY KEY, --RUT CHILENO CON PUNTOS Y CON GUIÓN
	"CLI_NOMBRE" VARCHAR(255), --PRIMER NOMBRE Y APELLIDOS
	"CLI_GIRO" VARCHAR(255), --LO QUE SUGIERAS
	"CLI_DIRECCION" VARCHAR(255), --CALLE NÚMERO COMUNA REGION
	"CLI_FONO" VARCHAR(20) --+569XXXXXXXX o 22XXXXXXX
);
	
CREATE TABLE "TB_VENTA"(
	"VEN_NUMERO" SERIAL PRIMARY KEY,
	"VEN_FECHA" DATE, --VENTAS AÑOS 2020 A 2024
	"TB_CLIENTE_CLI_RUT" VARCHAR(15)
);
	
CREATE TABLE "TB_DETALLE_VENTA"(
	"DET_ID" SERIAL PRIMARY KEY,
	"DET_CANTIDAD" SMALLINT CHECK ("DET_CANTIDAD" > 0),
	"DET_VALOR_UNITARIO" INTEGER CHECK ("DET_VALOR_UNITARIO" > 0),
	"TB_VENTA_VEN_NUMERO" INTEGER,
	"TB_PRODUCTO_PRO_CODIGO" VARCHAR(20)
);
	
CREATE TABLE "TB_PRODUCTO"(
	"PRO_CODIGO" VARCHAR(20) PRIMARY KEY,
	"PRO_NOMBRE" VARCHAR(255),
	"PRO_STOCK" SMALLINT,
	"PRO_VALOR_UNITARIO" INTEGER
);

ALTER TABLE "TB_VENTA"
ADD CONSTRAINT "TB_VENTA_FK" FOREIGN KEY ("TB_CLIENTE_CLI_RUT") REFERENCES "TB_CLIENTE"("CLI_RUT");
	
ALTER TABLE "TB_DETALLE_VENTA"
ADD CONSTRAINT "TB_DETALLE_VENTA_FK_PRODUCTO" FOREIGN KEY ("TB_PRODUCTO_PRO_CODIGO") REFERENCES "TB_PRODUCTO"("PRO_CODIGO");
	
ALTER TABLE "TB_DETALLE_VENTA"
ADD CONSTRAINT "TB_DETALLE_VENTA_FK_VENTA" FOREIGN KEY ("TB_VENTA_VEN_NUMERO") REFERENCES "TB_VENTA"("VEN_NUMERO");